# Read about `build.yaml` at https://pub.dartlang.org/packages/build_config
builders:
  chopper_generator:
    target: ":tectonic_chopper_generator"
    import: "package:tectonic_chopper_generator/tectonic_chopper_generator.dart"
    builder_factories: ["chopperGeneratorFactory"]
    build_extensions: {".dart": [".chopper.dart"]}
    auto_apply: root_package
    build_to: source